$(".post1").draggable()
$(".post2").draggable()
$(".post3").draggable()
$(".post4").draggable()
$(".post5").draggable()
$(".post6").draggable()
$(".post7").draggable()

$(".bgcred1").draggable()
$(".videolink").draggable()